Repository DeveloperAcademy-POSTECH/2024-NC2-A14-WeatherKit, pull requests merged in 2024-06, with the labels that each got.

#2 1 get single location
  .github/PULL_REQUEST_TEMPLATE.md
  WeatherPlan/WeatherPlan.xcodeproj/project.pbxproj
  WeatherPlan/WeatherPlan/Data/LocationManager.swift
Labels: enhancement

#4 #3 [Feat] WeatherUseCase 작성
  WeatherPlan/WeatherPlan/Data/LocationManager.swift
  WeatherPlan/WeatherPlan/Data/WeatherManager.swift
  WeatherPlan/WeatherPlan/Domain/Entity/WeatherModel.swift
  WeatherPlan/WeatherPlan/Domain/UseCase/WeatherUseCase.swift
  WeatherPlan/WeatherPlan/Domain/UseCase/interface/LocationInterface.swift
  WeatherPlan/WeatherPlan/Domain/UseCase/interface/WeatherInterface.swift
Labels: enhancement

#7 #6 [Feat] WeatherKit
  WeatherPlan/WeatherPlan.xcodeproj/project.pbxproj
  WeatherPlan/WeatherPlan/Data/WeatherManager.swift
  WeatherPlan/WeatherPlan/Domain/Entity/WeatherModel.swift
  WeatherPlan/WeatherPlan/Domain/UseCase/WeatherUseCase.swift
  WeatherPlan/WeatherPlan/UI/ContentView.swift
Labels: enhancement

#8 5 feat building view
  WeatherPlan/WeatherPlan.xcodeproj/project.pbxproj
  WeatherPlan/WeatherPlan/Data/WeatherManager.swift
  WeatherPlan/WeatherPlan/Domain/Entity/PlanModel.swift
  WeatherPlan/WeatherPlan/Domain/Entity/WeatherModel.swift
  WeatherPlan/WeatherPlan/Domain/UseCase/WeatherUseCase.swift
  WeatherPlan/WeatherPlan/UI/Components/OffsetKey.swift
  WeatherPlan/WeatherPlan/UI/ContentView.swift
  WeatherPlan/WeatherPlan/UI/Main/MainView.swift
  WeatherPlan/WeatherPlan/Utility/Date+Extensions.swift
  WeatherPlan/WeatherPlan/Utility/View+Extensions.swift
Labels: enhancement

#9 5 feat building view
  WeatherPlan/WeatherPlan.xcodeproj/project.pbxproj
  WeatherPlan/WeatherPlan/Domain/Entity/PlanModel.swift
  WeatherPlan/WeatherPlan/UI/Components/OffsetKey.swift
  WeatherPlan/WeatherPlan/UI/ContentView.swift
  WeatherPlan/WeatherPlan/UI/Main/MainView.swift
  WeatherPlan/WeatherPlan/Utility/Date+Extensions.swift
  WeatherPlan/WeatherPlan/Utility/View+Extensions.swift
Labels: enhancement

#11 10 feat complete weatherusecase data fetching
  WeatherPlan/WeatherPlan/Data/LocationManager.swift
  WeatherPlan/WeatherPlan/Data/WeatherManager.swift
  WeatherPlan/WeatherPlan/Domain/Entity/WeatherModel.swift
  WeatherPlan/WeatherPlan/Domain/UseCase/WeatherUseCase.swift
  WeatherPlan/WeatherPlan/Domain/UseCase/interface/WeatherInterface.swift
  WeatherPlan/WeatherPlan/UI/Main/MainView.swift
  WeatherPlan/WeatherPlan/Utility/Date+Extensions.swift
Labels: enhancement

#13 #12 [Feat] Weather Data to View
  WeatherPlan/WeatherPlan.xcodeproj/project.pbxproj
  WeatherPlan/WeatherPlan/Assets.xcassets/primary_black.colorset/Contents.json
  WeatherPlan/WeatherPlan/Assets.xcassets/primary_blue.colorset/Contents.json
  WeatherPlan/WeatherPlan/Assets.xcassets/primary_green.colorset/Contents.json
  WeatherPlan/WeatherPlan/Assets.xcassets/primary_red.colorset/Contents.json
  WeatherPlan/WeatherPlan/Assets.xcassets/primary_white.colorset/Contents.json
  WeatherPlan/WeatherPlan/Assets.xcassets/primary_yellow.colorset/Contents.json
  WeatherPlan/WeatherPlan/Domain/Entity/WeatherModel.swift
  WeatherPlan/WeatherPlan/UI/Main/MainView.swift
  WeatherPlan/WeatherPlan/UI/Record/PlanSheetView.swift
Labels: enhancement

#15 #14 [Feat] Plan Data System 구현 (in memory)
  WeatherPlan/WeatherPlan.xcodeproj/project.pbxproj
  WeatherPlan/WeatherPlan/Assets.xcassets/AppIcon.appiconset/AppIcon.png
  WeatherPlan/WeatherPlan/Assets.xcassets/AppIcon.appiconset/Contents.json
  WeatherPlan/WeatherPlan/Data/DataService.swift
  WeatherPlan/WeatherPlan/Data/WeatherManager.swift
  WeatherPlan/WeatherPlan/Domain/Entity/PlanModel.swift
  WeatherPlan/WeatherPlan/Domain/Entity/WeatherModel.swift
  WeatherPlan/WeatherPlan/Domain/UseCase/PlanUseCase.swift
  WeatherPlan/WeatherPlan/Domain/UseCase/interface/DataServiceInterface.swift
  WeatherPlan/WeatherPlan/UI/Components/EditType.swift
  WeatherPlan/WeatherPlan/UI/Main/MainView.swift
  WeatherPlan/WeatherPlan/UI/Record/PlanSheetView.swift
Labels: enhancement

#16 [Fix] 삭제완료시 sheet 내리기
  WeatherPlan/WeatherPlan/UI/Record/PlanSheetView.swift
Labels: bug

#19 18 docu readme update
  README.md
Labels: documentation

#20 #17 [Refactor] MainView 에서 Calendar, WeatherDetail, PlanList 분리
  WeatherPlan/WeatherPlan.xcodeproj/project.pbxproj
  WeatherPlan/WeatherPlan/Assets.xcassets/gradient_blue.colorset/Contents.json
  WeatherPlan/WeatherPlan/Assets.xcassets/gradient_red.colorset/Contents.json
  WeatherPlan/WeatherPlan/UI/Main/MainView+Calendar.swift
  WeatherPlan/WeatherPlan/UI/Main/MainView+PlanListView.swift
  WeatherPlan/WeatherPlan/UI/Main/MainView+WeatherDetail.swift
  WeatherPlan/WeatherPlan/UI/Main/MainView.swift
  WeatherPlan/WeatherPlan/UI/Record/PlanSheetView.swift
Labels: enhancement
